- name: Deploy to EC2
  uses: appleboy/ssh-action@v1
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USERNAME }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      docker pull ashwinisdocker/cicd-app:latest
      docker stop cicd-container || true
      docker rm cicd-container || true
      docker run -d -p 5000:5000 --name cicd-container ashwinisdocker/cicd-app:latest
